name: Run analyze and tests
on:
  pull_request:
    branches: [ main ]
jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
        working-directory: ./modlar
      - run: flutter analyze
        working-directory: ./modlar
      - run: flutter test
        working-directory: ./modlar

